T2CON   EQU 0C8H
RCAP2L  EQU 0CAH
RCAP2H  EQU 0CBH
TL2     EQU 0CCH
TH2     EQU 0CDH

TR2     BIT T2CON.2
TF2     BIT T2CON.7

SEG_PORT EQU P2
WEI_PORT EQU P1

BCD_K       EQU 30H
BCD_H       EQU 31H
DIGIT_INDEX EQU 32H
SCROLL_CNT  EQU 33H
SCROLL_POS  EQU 34H

; ????
ORG 0000H
MAIN:
    MOV T2CON, #00H
    CLR P1.3?

    MOV DIGIT_INDEX, #0   
    MOV SCROLL_CNT, #100  
    MOV SCROLL_POS, #0    

MAIN_LOOP:
    ACALL READ_ADC_AND_CONVERT

    JB P1.2, ANALOG_DUTY_MODE
    MOV R0, #20           
    SJMP FIXED_DUTY_CALC

ANALOG_DUTY_MODE:
    MOV A, P0
    MOV R0, A
    MOV A, R0
    MOV B, #20
    MUL AB
    MOV R6, A
    MOV R7, B
    MOV A, R7
    CJNE A, #13H, CHECK_HIGH_BYTE
    MOV A, R6
    CJNE A, #88H, CHECK_LOW_BYTE
    SJMP HIGH_TIME_CALCULATED

CHECK_LOW_BYTE:
    JC HIGH_TIME_CALCULATED
    SJMP APPLY_CAP

CHECK_HIGH_BYTE:
    JC HIGH_TIME_CALCULATED

APPLY_CAP:
    MOV R7, #13H
    MOV R6, #88H

HIGH_TIME_CALCULATED:
    MOV A, #88H
    CLR C
    SUBB A, R6
    MOV R4, A
    MOV A, #13H
    SUBB A, R7
    MOV R5, A
    SJMP TIMES_CALCULATED

FIXED_DUTY_CALC:
    MOV A, R0
    MOV B, #87          
    MUL AB
    MOV R6, A
    MOV R7, B
    MOV A, #88H        
    CLR C
    SUBB A, R6          
    MOV R4, A
    MOV A, #13H         
    SUBB A, R7            
    MOV R5, A

TIMES_CALCULATED:
    SETB P1.3            
    MOV A, R6
    MOV R6, A
    MOV A, R7
    MOV R7, A
    ACALL DELAY_US

    CLR P1.3           
    MOV A, R4
    MOV R6, A
    MOV A, R5
    MOV R7, A
    ACALL DELAY_US

    ACALL DISPLAY_SCAN_MODIFIED

    SJMP MAIN_LOOP

READ_ADC_AND_CONVERT:
    MOV A, P0
    MOV R0, A
    MOV B, #50
    MUL AB
    MOV A, B
    MOV B, #10
    DIV AB
    MOV BCD_K, A
    MOV BCD_H, B
    RET

DISPLAY_SCAN_MODIFIED:
    MOV A, DIGIT_INDEX
    CJNE A, #0, NOT_DIGIT0_MOD
    MOV DPTR, #NUMBCY
    MOV A, SCROLL_POS
    MOVC A, @A+DPTR
    SJMP DISPLAY_DIGIT_MOD

NOT_DIGIT0_MOD:
    CJNE A, #1, NOT_DIGIT1_MOD
    MOV DPTR, #NUMBCY
    MOV A, SCROLL_POS
    INC A
    ANL A, #07H         
    MOVC A, @A+DPTR
    SJMP DISPLAY_DIGIT_MOD

NOT_DIGIT1_MOD:
    CJNE A, #2, NOT_DIGIT2_MOD
    MOV A, BCD_K
    SJMP DISPLAY_DIGIT_MOD

NOT_DIGIT2_MOD:
    CJNE A, #3, NOT_DIGIT3_MOD
    MOV A, BCD_H
    SJMP DISPLAY_DIGIT_MOD

NOT_DIGIT3_MOD:
    MOV SEG_PORT, #0FFH

DISPLAY_DIGIT_MOD:
    MOV DPTR, #TABLE
    MOVC A, @A+DPTR

    MOV R0, DIGIT_INDEX
    CJNE R0, #2, NO_DP_POINT
    ANL A, #01111111B     

NO_DP_POINT:
    MOV SEG_PORT, A
   
DISPLAY_OUTPUT:
    MOV DPTR, #PICK_POS_MODIFIED
    MOV A, DIGIT_INDEX
    MOVC A, @A+DPTR
    MOV WEI_PORT, A

    INC DIGIT_INDEX
    MOV A, DIGIT_INDEX
    CJNE A, #4, DISPLAY_END_MOD
    MOV DIGIT_INDEX, #0

    DJNZ SCROLL_CNT, DISPLAY_END_MOD
    MOV SCROLL_CNT, #25   
    INC SCROLL_POS
    MOV A, SCROLL_POS
    ANL A, #07H
    MOV SCROLL_POS, A

DISPLAY_END_MOD:
    RET


DELAY_US:
    MOV A, R6
    CPL A
    ADD A, #1
    MOV TL2, A

    MOV A, R7
    CPL A
    ADDC A, #0
    MOV TH2, A

    CLR TF2
    SETB TR2

WAIT_TIMER:
    JNB TF2, WAIT_TIMER
    CLR TR2
    CLR TF2
    RET

NUMBCY:
    DB 0,8,1,0,0,4

TABLE:
    DB 0C0H,0F9H,0A4H,0B0H,099H,92H,82H,0F8H,80H,90H

PICK_POS_MODIFIED:
    DB 11101111B    ; P1.4
    DB 11011111B    ; P1.5
    DB 10111111B    ; P1.6
    DB 01111111B    ; P1.7
END
